name: Keybox Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
          TELEGRAM_THREAD_ID_2: ${{ secrets.TELEGRAM_THREAD_ID_2 }}
        run: python check_file.py

      - name: Save state
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Аккуратно сохраняем каждый файл, если он существует
          if [ -f last_hash.txt ]; then git add last_hash.txt; fi
          if [ -f last_msg_id_1.txt ]; then git add last_msg_id_1.txt; fi
          if [ -f last_msg_id_2.txt ]; then git add last_msg_id_2.txt; fi
          
          git commit -m "Update state" || exit 0
          git push
          
